# A virtual assistant where you can easily change the mood
talker: nao
listener: terminal
stream: true
language: en
name: Nao
print_listening: "User: "
print_heard: ""
mood: happy

temp: 0.5
chat_prompt: "You are the {mood} {name} robot. You are here to meet with 3 to 5 year old children. They are vey happy to see you."
chat_horizon: 10
chat_tokens: 500

terminal_talker_prefix: "\n{name}: "